### ISSUE TITLE
b+b editor background is linked to the mutedBackgroundColor

### ISSUE THREAD

**Issue by IvanMaldonado** [LMMS/lmms#2634]
![captura de pantalla_2016-03-04_17-37-44](https://cloud.githubusercontent.com/assets/12549082/13543331/eedabfa0-e22f-11e5-806b-e54cc95ca6b6.png)

![captura de pantalla_2016-03-04_17-38-28](https://cloud.githubusercontent.com/assets/12549082/13543332/ef2d0a62-e22f-11e5-90d5-14dc1e167a5a.png)
```css
TrackContentObjectView   {
	qproperty-mutedColor: rgb( 128, 128, 128 );
	qproperty-mutedBackgroundColor: rgb( 80, 80, 80 );  /* <-- This one in the style.css */
	qproperty-selectedColor: rgb( 0, 125, 255 );
	qproperty-textColor: rgb( 255, 255, 255 );
	qproperty-textShadowColor: rgb( 0, 0, 0 );
	qproperty-gradient: false;
}
```
