### ISSUE TITLE
Split CSS file into smaller ones

### ISSUE THREAD

**Issue by winniehell** [LMMS/lmms#5120]
The [current stylesheet](https://github.com/LMMS/lmms/blob/stable-1.2/data/themes/default/style.css) is almost 1000 lines long. That is quite a lot. I'd like to suggest to split it into smaller files by the top level widget the styles are affecting.

For example

```css
QTreeView {
	outline: none;
}

QTreeWidget::item:hover,
QTreeWidget::branch:hover {
	background-color: #3C444E;
}
```

would go into a `QTreeWidget.css`.

Some styles that affect a group of unrelated widget may still end up in a special `global.css` such as these lines:

```css
QLabel, QTreeWidget, QListWidget, QGroupBox, QMenuBar {
	color: #d1d8e4;
}
```

Hopefully these will relatively few though.

---

The advantages of splitting into smaller files would be:

- merge conflicts are less likely to happen
- styles for a certain component are easier to find (`AutomationEditor.cpp` --> `AutomationEditor.css`)

In the future this may also allow to inherit from the default theme and only override the styles for some components.

---

The technical side of this is fairly simple: Because the Qt Resource System allows to list files in the resource directories, we can simply load all `*.css` files.
