### ISSUE TITLE
Include "background art" per Theme

### ISSUE THREAD

**Issue by ghost** [LMMS/lmms#6084]
### Enhancement Summary
Would be nice if you could have a "background art" image for each theme. The file would be included as a png or jpg and would be defined in style.css
```
BackgroundArt {
	image: url("resources: bg.png");
}
```

Of course if the user has chosen their own custom background art in Settings, then that'd take priority over the theme one. (or they could be asked when the theme is first changed).

#### Justification
A theme usually includes every presentational element. 
Say if you have a theme called "underwater". It'd be cool to be able to include a photo of the ocean deep along with the aquatic UI styling.
Or if the theme is based off a video game character, it'd be cool to ship an artwork with them to be used as background. It'd make it more "complete".

**Comment by rubiefawn** [comment]
You can already do this by including the following rule in a theme's `style.css`:

```css
/* example taken from data/themes/classic/style.css */
QMdiArea {
	background-image: url("resources:background_artwork.png");
}
```

The rule is also present in the default theme, which uses `background-color` instead:

```css
/* example taken from data/themes/default/style.css */
QMdiArea {
	background-color: #111314;
}
```
